import BangunRuang, luasbangundatar

print("Kotak")
print("Luas kubus dengan sisi 2         :", BangunRuang.Lkubus(2))
print("Luas persegi dengan sisi 2       :", luasbangundatar.Lpersegi(2))
print("Keliling persegi dengan sisi  2  :", luasbangundatar.Kpersegi(2))
print()
print("Luas balok dengan panjang 2, lebar 4, dan tinggi 5       :", BangunRuang.Lbalok(2,4,5))
print("Luas persegi panjang dengan panjang 2, lebar 4           :", luasbangundatar.Lpersegipanjang(2,4))
print("Kelilinng persegi panjang dengan panja 2, dan lebar 4    :", luasbangundatar.Kpersegipanjang(2,4))
print()
print("Segitiga")
print("Luas prisma segitiga dengan Lsisi:150, Kalas:48, dan Tinggi:25   :", BangunRuang.Lprisma(150,48,25))
print("Keliling segitiga dengan sisi1 12, sisi2 18, dan sisi3 18        :", luasbangundatar.Ksegitiga(12,18,18))
print("Luas segitiga dengan alas 12 dan tinggi 25                       :", luasbangundatar.Lsegitiga(12,25))
print()
print("Bulat")
print("Luas tabung dengan jari2 12 dan tinggi 25        :", BangunRuang.Ltabung(12,25))
print("Keliling lingkaran dengan jari2 12               :", luasbangundatar.Klingkaran(12))
print("Luas lingkaran dengan jari2 12                   :", luasbangundatar.Llingkaran(12))
print()
print("Luas kerucut dengan jari2 12 dan sisi 25     :", BangunRuang.Lkerucut(12,25))
print()
print("Jajar Genjang")
print("Keliling jajar genjang dengan panjang 12 dan lebar 18    :", luasbangundatar.Kjajargenjang(12,18,))
print("Luas jajar genjang dengan panjang 12 dan tinggi 25       :", luasbangundatar.Ljajargenjang(12,25))